[package]
name = "git-gone"
version = "0.3.2"
description = "Manage \"gone\" Git branches"
homepage = "https://github.com/lunaryorn/git-gone"
repository = "https://github.com/lunaryorn/git-gone"
readme = "git-gone.1.adoc"
license = "Apache-2.0"
keywords = ["git", "branch", "remote"]
categories = ["development-tools", "command-line-utilities"]
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
include = ["git-gone.1", "git-gone.1.adoc"]

[dependencies]
clap = "^2"
git2 = "^0.13"
