name: Release

on:
  push:
    tags:
      - v*

jobs:
  unix:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        include:
          - os: macOS-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: cargo test --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: strip
        run: strip 'target/${{ matrix.target }}/release/mdcat'
        if: "!contains(matrix.target, 'windows')"
      - uses: olegtarasov/get-tag@v1
      - name: Build package
        id: package
        shell: bash
        run: |
          ARCHIVE_NAME="git-gone-${GITHUB_TAG_NAME}-${{ matrix.target }}"
          if [[ '${{ matrix.target }}' == *windows* ]]; then
            ARCHIVE_FILE="${ARCHIVE_NAME}.zip"
            mv LICENSE LICENSE.txt
            7z a "${ARCHIVE_FILE}" "./target/${{ matrix.target }}/release/mdcat.exe" ./README.md ./CHANGELOG.md ./LICENSE.txt
            echo ::set-output "name=file::${ARCHIVE_FILE}"
            echo ::set-output "name=name::${ARCHIVE_NAME}.zip"
          else
            ARCHIVE_FILE="/tmp/${ARCHIVE_NAME}.tar.gz"
            mkdir "/tmp/${ARCHIVE_NAME}"
            cp README.md CHANGELOG.md LICENSE "target/${{ matrix.target }}/release/mdcat" "/tmp/${ARCHIVE_NAME}"
            tar -czf "${ARCHIVE_FILE}" -C /tmp/ "${ARCHIVE_NAME}"
            echo ::set-output "name=file::${ARCHIVE_FILE}"
            echo ::set-output "name=name::${ARCHIVE_NAME}.tar.gz"
          fi
      - name: Upload package
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.file }}
          asset_name:  ${{ steps.package.outputs.name }}
          tag: ${{ github.ref }}
          overwrite: true
